spring:
  application:
    name: configure-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/JWXYZ/springcouldconfigure
          search-paths: swallow
          password:
          username:
          skip-ssl-validation: true

      label: mater
server:
  port: 8766
