spring:
  application:
    name: configure-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/JWXYZ/swallow.git
          search-paths: swallow
          password:
          username:

      label: mater
server:
  port: 8766
