server:
  port: 8769
spring:
  application:
    name: eureka-server-configure
  cloud:
    config:
      server:
        git:
          uri: https://github.com/JWXYZ/springcouldconfigure/
          search-paths: configures
          password:
          username:
          skip-ssl-validation: true
      label: master

  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
