server:
  port: 8761
spring:
  profiles:
    active: peer1
eureka:
  instance:
    hostname: peer1
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://peer2:8769/eureka/,http://peer3:8768/eureka/
    register-with-eureka: false
    fetch-registry: false